services:
  ultrafeeder:
    image: ghcr.io/jquagga/ureadsb:main@sha256:595bfb648066c0995ad204580d4b426d8059605e2c1846e236eb3993864a350f
    container_name: ultrafeeder
    hostname: ultrafeeder
    restart: unless-stopped
    volumes:
      - readsb:/run/readsb
      - /opt/adsb/uuid:/run/uuid:ro
    # ports:
    #   - 30006:30006 # BeastReduce for local polling
    #   - 30152:30152 # api port
    devices:
      - "/dev/bus/usb:/dev/bus/usb:rwm"
    command: "--device-type=rtlsdr --gain=ADSB_SDR_GAIN --device=ADSB_SDR_SERIAL --ppm=ADSB_SDR_PPM --lat=FEEDER_LAT --lon=FEEDER_LONG --quiet --uuid-file=/run/uuid --db-file=/usr/local/share/tar1090/aircraft.csv.gz --db-file-lt --write-json=/run/readsb --json-trace-interval=15 --json-reliable=1 --net --net-bi-port=30004,30104 --net-bo-port=30005 --net-beast-reduce-out-port=30006 --net-ro-interval-beast-reduce=0.12 --net-beast-reduce-interval=0.5 --net-api-port 30152 --net-connector=feed.adsb.fi,30004,beast_reduce_plus_out --net-connector=in.adsb.lol,30004,beast_reduce_plus_out --net-connector=feed.airplanes.live,30004,beast_reduce_plus_out --net-connector=feed.theairtraffic.com,30004,beast_reduce_plus_out --net-connector=data.avdelphi.com,24999,beast_reduce_plus_out --net-connector=skyfeed.hpradar.com,30004,beast_reduce_plus_out --net-connector=dati.flyitalyadsb.com,4905,beast_reduce_plus_out --net-connector=feed1.adsbexchange.com,30004,beast_reduce_plus_out --net-connector=dump978,30978,uat_in"
  dump978:
    image: ghcr.io/jquagga/u978:main@sha256:9ae714d17c6dae17eb927908b0005f2b22b2bc65456f0d47a0a4e0123b24fdf4
    container_name: dump978
    hostname: dump978
    restart: unless-stopped
    devices:
      - "/dev/bus/usb:/dev/bus/usb:rwm"
    command: "--sdr driver=rtlsdr,serial=978 --raw-port 0.0.0.0:30978 --format CS8"
  mlat-adsb-fi:
    image: ghcr.io/jquagga/umlat:main@sha256:aa83fc1a2ef973a9bd23b4667e9a8931116a611358025854239b060288fa5b30
    container_name: umlat-adsb-fi
    hostname: umlat-adsb-fi
    restart: unless-stopped
    depends_on:
      - ultrafeeder
    command: "--privacy --input-type beast --input-connect ultrafeeder:30005 --server feed.adsb.fi:31090 --results beast,connect,ultrafeeder:30004 --uuid ULTRAFEEDER_UUID --user FEEDER_NAME --lat FEEDER_LAT --lon FEEDER_LONG --alt FEEDER_ALT_Mm"
  mlat-adsb-lol:
    image: ghcr.io/jquagga/umlat:main@sha256:aa83fc1a2ef973a9bd23b4667e9a8931116a611358025854239b060288fa5b30
    container_name: umlat-adsb-lol
    hostname: umlat-adsb-lol
    restart: unless-stopped
    depends_on:
      - ultrafeeder
    command: "--privacy --input-type beast --input-connect ultrafeeder:30005 --server in.adsb.lol:31090 --results beast,connect,ultrafeeder:30004 --uuid ULTRAFEEDER_UUID --user FEEDER_NAME --lat FEEDER_LAT --lon FEEDER_LONG --alt FEEDER_ALT_Mm"
  mlat-airplanes-live:
    image: ghcr.io/jquagga/umlat:main@sha256:aa83fc1a2ef973a9bd23b4667e9a8931116a611358025854239b060288fa5b30
    container_name: umlat-airplanes-live
    hostname: umlat-airplanes-live
    restart: unless-stopped
    depends_on:
      - ultrafeeder
    command: "--privacy --input-type beast --input-connect ultrafeeder:30005 --server feed.airplanes.live:31090 --results beast,connect,ultrafeeder:30004 --uuid ULTRAFEEDER_UUID --user FEEDER_NAME --lat FEEDER_LAT --lon FEEDER_LONG --alt FEEDER_ALT_Mm"
  mlat-adsbex:
    image: ghcr.io/jquagga/umlat:main@sha256:aa83fc1a2ef973a9bd23b4667e9a8931116a611358025854239b060288fa5b30
    container_name: umlat-adsbex
    hostname: umlat-adsbex
    restart: unless-stopped
    depends_on:
      - ultrafeeder
    command: "--privacy --input-type beast --input-connect ultrafeeder:30005 --server feed.adsbexchange.com:31090 --results beast,connect,ultrafeeder:30004 --uuid ULTRAFEEDER_UUID --user FEEDER_NAME --lat FEEDER_LAT --lon FEEDER_LONG --alt FEEDER_ALT_Mm"
  piaware:
    image: ghcr.io/jquagga/upiaware:main@sha256:624b764046b21c54da11233c69199ecf6d9aa3e0de3b88b9791fd507ec31ddae
    container_name: piaware
    restart: unless-stopped
    depends_on:
      - ultrafeeder
    volumes:
      - /opt/adsb/piaware.conf:/etc/piaware.conf:ro
  upa:
    image: ghcr.io/jquagga/upa:main@sha256:6d470fb67966c073bb9523c7ee4a528a2d358717c82d5a958a55d2e16cc7a5d8
    container_name: upa
    hostname: upa
    restart: unless-stopped
    depends_on:
      - ultrafeeder
    environment:
      - UPA_NOTIFY_URL=${UPA_NOTIFY_URL}
      - UPA_PADATABASE_URL=${UPA_PADATABASE_URL}
    #  - UPA_JSON_URL=http://ultrafeeder:30152/?all_with_pos
  utar1090:
    image: ghcr.io/jquagga/utar1090:main@sha256:67b9ee7f8d87de0055f96dceb64b16d16a6897d43591dafc266761271268f0bd
    restart: unless-stopped
    container_name: tar1090
    depends_on:
      - ultrafeeder
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - readsb:/srv/data:ro
      - caddy_data:/data
      - caddy_config:/config
  watchtower:
    image: containrrr/watchtower:latest@sha256:6dd50763bbd632a83cb154d5451700530d1e44200b268a4e9488fefdfcf2b038
    container_name: watchtower
    depends_on:
      - ultrafeeder
    restart: always
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=21600 # 6 hours
      - WATCHTOWER_INCLUDE_RESTARTING=true # This restarts containers in "restarting" status AKA broken. Watchtower already restarts normal containers.
      - WATCHTOWER_ROLLING_RESTART=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  readsb:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "size=256m,uid=65532"
  caddy_data:
  caddy_config: