services:
  ultrafeeder:
    image: ghcr.io/jquagga/ureadsb:main@sha256:0d4606545b2cface8575ec2809509c1da29fa8748ab2db096ae324da91b4b07b
    container_name: ultrafeeder
    hostname: ultrafeeder
    restart: unless-stopped
    volumes:
      - readsb:/run/readsb
      - /opt/adsb/uuid:/run/uuid:ro
    # ports:
    #   - 30006:30006 # BeastReduce for local polling
    #   - 30152:30152 # api port
    devices:
      - "/dev/bus/usb:/dev/bus/usb:rwm"
    command: "--device-type=rtlsdr --gain=ADSB_SDR_GAIN --device=ADSB_SDR_SERIAL --ppm=ADSB_SDR_PPM --lat=FEEDER_LAT --lon=FEEDER_LONG --quiet --uuid-file=/run/uuid --db-file=/usr/local/share/tar1090/aircraft.csv.gz --db-file-lt --write-json=/run/readsb --json-trace-interval=15 --json-reliable=1 --net --net-heartbeat=35 --net-bi-port=30004,30104 --net-bo-port=30005 --net-beast-reduce-out-port=30006 --net-beast-reduce-interval=0.5 --net-api-port 30152 --net-connector=feed.adsb.fi,30004,beast_reduce_plus_out --net-connector=in.adsb.lol,30004,beast_reduce_plus_out --net-connector=feed.airplanes.live,30004,beast_reduce_plus_out --net-connector=feed.planespotters.net,30004,beast_reduce_plus_out --net-connector=feed.theairtraffic.com,30004,beast_reduce_plus_out --net-connector=data.avdelphi.com,24999,beast_reduce_plus_out --net-connector=skyfeed.hpradar.com,30004,beast_reduce_plus_out --net-connector=dati.flyitalyadsb.com,4905,beast_reduce_plus_out --net-connector=feed1.adsbexchange.com,30004,beast_reduce_plus_out --net-connector=dump978,30978,uat_in"
  dump978:
    image: ghcr.io/jquagga/u978:main@sha256:5b688bb10c24b0e571c92919cadd3f2fa3c6175275aea2239fe938264a64ab19
    container_name: dump978
    hostname: dump978
    restart: unless-stopped
    devices:
      - "/dev/bus/usb:/dev/bus/usb:rwm"
    command: "--sdr driver=rtlsdr,serial=978 --raw-port 0.0.0.0:30978 --format CS8"
  mlat-adsb-fi:
    image: ghcr.io/jquagga/umlat:main@sha256:ba98a0f7fb0f4ccc4efbdee01572de81887d1cb7db393fe0566ad73c97e0a293
    container_name: umlat-adsb-fi
    hostname: umlat-adsb-fi
    restart: unless-stopped
    depends_on:
      - ultrafeeder
    command: "--privacy --input-type beast --input-connect ultrafeeder:30005 --server feed.adsb.fi:31090 --results beast,connect,ultrafeeder:30004 --uuid ULTRAFEEDER_UUID --user FEEDER_NAME --lat FEEDER_LAT --lon FEEDER_LONG --alt FEEDER_ALT_Mm"
  mlat-adsb-lol:
    image: ghcr.io/jquagga/umlat:main@sha256:ba98a0f7fb0f4ccc4efbdee01572de81887d1cb7db393fe0566ad73c97e0a293
    container_name: umlat-adsb-lol
    hostname: umlat-adsb-lol
    restart: unless-stopped
    depends_on:
      - ultrafeeder
    command: "--privacy --input-type beast --input-connect ultrafeeder:30005 --server in.adsb.lol:31090 --results beast,connect,ultrafeeder:30004 --uuid ULTRAFEEDER_UUID --user FEEDER_NAME --lat FEEDER_LAT --lon FEEDER_LONG --alt FEEDER_ALT_Mm"
  mlat-airplanes-live:
    image: ghcr.io/jquagga/umlat:main@sha256:ba98a0f7fb0f4ccc4efbdee01572de81887d1cb7db393fe0566ad73c97e0a293
    container_name: umlat-airplanes-live
    hostname: umlat-airplanes-live
    restart: unless-stopped
    depends_on:
      - ultrafeeder
    command: "--privacy --input-type beast --input-connect ultrafeeder:30005 --server feed.airplanes.live:31090 --results beast,connect,ultrafeeder:30004 --uuid ULTRAFEEDER_UUID --user FEEDER_NAME --lat FEEDER_LAT --lon FEEDER_LONG --alt FEEDER_ALT_Mm"
  mlat-planespotters:
    image: ghcr.io/jquagga/umlat:main@sha256:ba98a0f7fb0f4ccc4efbdee01572de81887d1cb7db393fe0566ad73c97e0a293
    container_name: umlat-planespotters
    hostname: umlat-planespotters
    restart: unless-stopped
    depends_on:
      - ultrafeeder
    command: "--privacy --input-type beast --input-connect ultrafeeder:30005 --server mlat.planespotters.net:31090 --results beast,connect,ultrafeeder:30004 --uuid ULTRAFEEDER_UUID --user FEEDER_NAME --lat FEEDER_LAT --lon FEEDER_LONG --alt FEEDER_ALT_Mm"
  mlat-adsbex:
    image: ghcr.io/jquagga/umlat:main@sha256:ba98a0f7fb0f4ccc4efbdee01572de81887d1cb7db393fe0566ad73c97e0a293
    container_name: umlat-adsbex
    hostname: umlat-adsbex
    restart: unless-stopped
    depends_on:
      - ultrafeeder
    command: "--privacy --input-type beast --input-connect ultrafeeder:30005 --server feed.adsbexchange.com:31090 --results beast,connect,ultrafeeder:30004 --uuid ULTRAFEEDER_UUID --user FEEDER_NAME --lat FEEDER_LAT --lon FEEDER_LONG --alt FEEDER_ALT_Mm"
  piaware:
    image: ghcr.io/jquagga/upiaware:main@sha256:7646a502b983fa48ee80c714e194e7548909b3f36b92c967bdafe71a0c6e9e72
    container_name: piaware
    restart: unless-stopped
    depends_on:
      - ultrafeeder
    volumes:
      - /opt/adsb/piaware.conf:/etc/piaware.conf:ro
  upa:
    image: ghcr.io/jquagga/upa:main@sha256:7b2857a01b95bccdc53b05d60be837be56db5d568e047ff3b092affa005d834f
    container_name: upa
    hostname: upa
    restart: unless-stopped
    depends_on:
      - ultrafeeder
    environment:
      - UPA_NOTIFY_URL=${UPA_NOTIFY_URL}
      - UPA_PADATABASE_URL=${UPA_PADATABASE_URL}
    #  - UPA_JSON_URL=http://ultrafeeder:30152/?all_with_pos
  utar1090:
    image: ghcr.io/jquagga/utar1090:main@sha256:17fe64e4ec699ac3e67db257098cde43ed75e69acac8a343752986b46780d84f
    restart: unless-stopped
    container_name: tar1090
    depends_on:
      - ultrafeeder
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - readsb:/srv/data:ro
      - caddy_data:/data
      - caddy_config:/config
  watchtower:
    image: containrrr/watchtower:latest@sha256:6dd50763bbd632a83cb154d5451700530d1e44200b268a4e9488fefdfcf2b038
    container_name: watchtower
    depends_on:
      - ultrafeeder
    restart: always
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=21600 # 6 hours
      - WATCHTOWER_INCLUDE_RESTARTING=true # This restarts containers in "restarting" status AKA broken. Watchtower already restarts normal containers.
      - WATCHTOWER_ROLLING_RESTART=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  readsb:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "size=256m,uid=65532"
  caddy_data:
  caddy_config: